### ISSUE TITLE
[app-scene-select] click events not firing

### ISSUE THREAD

**Issue by hughsk** [video-thing/app#4]
Total mercury noob so not sure what's causing this... Any ideas @yoshuawuyts?

**Comment by yoshuawuyts** [comment]
`ev-click` should be working... https://github.com/video-thing/app/search?utf8=%E2%9C%93&q=click

I'll look into it.

**Comment by hughsk** [comment]
From [virtual-hyperscript](https://github.com/Raynos/virtual-hyperscript):

> **Note:** You must create an instance of `dom-delegator` for `ev-*` to work.

Investigating :)
